language: java
script: travis_wait 60 mvn test -Pnolog,$TEST_EXECUTION_PROFILE
jdk:
  - oraclejdk8
env:
  - TEST_EXECUTION_PROFILE=test
  - TEST_EXECUTION_PROFILE=accumulo-test
  - TEST_EXECUTION_PROFILE=cypher-test
  - TEST_EXECUTION_PROFILE=elasticsearch-test
  - TEST_EXECUTION_PROFILE=es5-multimodule-test
branches:
  only:
    - master
    - 2.5.x
    - 3.2.x
addons:
  apt:
    packages:
      - oracle-java8-installer
